### ISSUE TITLE
[BUG] Error after local installation

### ISSUE THREAD

**Issue by MuratDoganer** [qrev-ai/qrev#18]
**Describe the bug**
Followed the instructions for local dev installation, I get a long error list after running `npm start` in the `client` folder

**To Reproduce**
1. Follow steps for installation
2. Run `npm start` in Client folder
3. Visit localhost:3000 for dev

**Screenshots**
I have created an ubuntu pastebin here with the errors, since its too long to post here:
https://pastebin.ubuntu.com/p/TqYYyHkz6M/

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Latest

**Additional context**
<img width="1280" alt="Screenshot 2024-07-31 at 14 56 51" src="https://github.com/user-attachments/assets/1ed8e70c-ff57-40fb-96a4-bbc61b652f90">

**Comment by sudhamabhatia** [comment]
hi there, sincere apologies for missing this. Will look into this and revert

**Comment by sanjay-gr-qrev** [comment]
@MuratDoganer Thanks for pointing out this issue.  We've found the fix for this issue but another one popped up. Looking into that and will release it soon

**Comment by MuratDoganer** [comment]
Thanks @sanjay-gr-qrev :) 

If there is any way I can help let me know!
